Repository SangKa/MobX-Docs-CN, pull requests merged in 2018-09, with the labels that each got.

#50 add button close tag
  docs/refguide/observer-component.md
Labels: typo

#51 Update react.md
  docs/best/react.md
Labels: polish, typo

#52 fix: wrong translation
  docs/best/react-performance.md
Labels: translation problem
